version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      - ${PWD}/lab_assistant_api/ddl:/lab_assistant_api/ddl
      - /shared/mariadb:/shared
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab_assistant
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   volumes:
  #     - ${PWD}/mongo:/data/db
  #     - /shared/mongo:/shared
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   tty: true
  #   privileged: true
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  lab_assistant_api:
    build: ${PWD}/lab_assistant_api
    image: naoto24kawa/lab_assistant_api:1.0
    container_name: lab_assistant_api
    restart: always
    volumes:
      - ${PWD}/lab_assistant_api:/lab_assistant_api
      - /shared/lab_assistant_api:/shared
    expose:
     - 3000
    ports:
      - 13000:3000
    depends_on:
      - mariadb
      # - mongo
    environment:
      VIRTUAL_HOST: lab_assistant_api.elchika.club
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: /bin/sh -c "npm i && npm start"
  lab_assistant:
    build: ${PWD}/lab_assistant
    image: naoto24kawa/lab_assistant:1.0
    container_name: lab_assistant
    restart: always
    volumes:
      - ${PWD}/lab_assistant:/lab_assistant
      - /shared/lab_assistant:/shared
    expose:
     - 3000
    ports:
      - 23000:3000
    depends_on:
      - mariadb
      # - mongo
    environment:
      VIRTUAL_HOST: lab_assistant.elchika.club
    tty: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: /bin/sh -c "npm i && npm start"

networks:
  default:
    external:
      name: common_link
