version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    networks:
      - bridge_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab_assistant
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ${PWD}/mongo:/data/db
    networks:
      - bridge_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  lab_assistant_api:
    build: ${PWD}/lab_assistant_api
    image: naoto24kawa/lab_assistant_api:0.1
    container_name: lab_assistant_api
    restart: always
    volumes:
      - ${PWD}/lab_assistant_api:/lab_assistant_api
    ports:
      - "13000:3000"
    networks:
      - bridge_network
    depends_on:
      - mariadb
      - mongo
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: /bin/sh -c "npm i && npm start"
  lab_assistant:
    build: ${PWD}/lab_assistant
    image: naoto24kawa/lab_assistant:0.1
    container_name: lab_assistant
    restart: always
    volumes:
      - ${PWD}/lab_assistant:/lab_assistant
    ports:
      - "23000:3000"
    networks:
      - bridge_network
    depends_on:
      - mariadb
      - mongo
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: /bin/sh -c "npm i && npm start"

networks:
  bridge_network:
