version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    networks:
      - bridge_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab_assistant
      MYSQL_USER:: lab_assistant
      MYSQL_PASSWORD: password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ${PWD}/mongo:/data/db
    networks:
      - bridge_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  lab_assistant_api:
    build: ${PWD}/lab_assistant_api
    image: naoto24kawa/lab_assistant_api:0.1
    container_name: lab_assistant_api
    restart: always
    volumes:
      - ${PWD}/lab_assistant_api:/usr/src/plise_api
    ports:
      - "13000:3000"
    networks:
      - bridge_network
    depends_on:
      - mysql
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  lab_assistant:
    build: ${PWD}/lab_assistant
    image: naoto24kawa/lab_assistant:0.1
    container_name: lab_assistant
    restart: always
    volumes:
      - ${PWD}/lab_assistant:/lab_assistant
    ports:
      - "23000:3000"
    networks:
      - bridge_network
    depends_on:
      - mysql
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bridge_network:
