kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app-deploy
        image: nginx:1.7.9
        ports:
        - containerPort: 80
